---
    
- name: Restart apache server
  service: 
    name: "{{ apache_service }}"
    state: restarted
    enabled: yes

- name: Test PHP info page
  uri:
    url: "http://localhost:{{ apache_listen_port }}/info.php"    
  changed_when: False