---

- name: Reload apache server
  service:
    name: "{{ apache_service }}"
    state: reloaded
    enabled: yes

- name: Restart apache server
  service:
    name: "{{ apache_service }}"
    state: restarted
    enabled: yes

- name: Test if Apache is installed and running
  uri:
    url: "http://localhost:{{ apache_listen_port }}"    
  changed_when: False